name: Lint and Secret Scan

on: [push]

jobs:
  static_analysis:
    name: lint and secret scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run -v ${{github.workspace}}:/path ghcr.io/gitleaks/gitleaks:latest detect -v --source="/path"
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: ${{vars.LINT_FILE_PATH}}
          # file_glob: "apimartifacts/apis/**/*.json"
