name: Lint and Secret Scan

on:
  push:
    branches-ignore:
      - main
      - integration

jobs:
  static_analysis:
    name: lint and secret scan
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Secret scan
        run: docker run -v ${{github.workspace}}:/path ghcr.io/gitleaks/gitleaks:latest detect -v --source="/path"
      - name: Lint
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: ${{secrets.LINT_FILE_PATH}}
