name: Lint and Secret Scan

on:
  push:
    branches-ignore:
      - main
      - integration

jobs:
  static_analysis:
    name: lint and secret scan
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Secret scan
        run: docker run -v ${{github.workspace}}:/path ghcr.io/gitleaks/gitleaks:latest detect -v --source="/path"
      - name: Lint
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: ${{secrets.LINT_FILE_PATH}}
      - name: Use dev environment secrets
        run: |
          echo "Using secret MY_SECRET: ${{ secrets.LINT_FILE_PATH }}"
          echo "Using variable MY_VARIABLE: ${{ vars.LINT_FILE_PATH }}"
